import pyautogui
import time
time.sleep(3)
c_banks="ADBL,BOKL,civil bank,CCBL,CZBIL,EBL,GBIME,KBL,LBL,MBL,MEGA,NABIL,NBB,NBL,NCCB,NICA,NMB,PCBL,PRVU,SANIMA,SBI,SBL,SCB,SRBL"
d_banks="CORBL,EDBL,GBBL,GRDBL,JBBL,KRBL,KSBBL,LBBL,MDB,MLBL,MNBBL,NABBC,SADBL,SAPDBL,SHINE,SINDU" 
micros= "ACLBSL,ALBSL,CBBL,civil lag,DDBL,FMDBL,FOWAD,GBLBS,GILB,GLBSL,GMFBS,ILBS,JSLBB,KLBSL,KMCDB,LLBS,MERO,MLBBL,MLBSL,MMFDB,MSLB,NICLBSL,NLBBL,NMBMF,NMFBS,NUBL,RMDC,RSDC,SABSL,SDLBSL,SKBBL,SLBBL,SLBS,SLBSL,SMATA,SMB,SMFBS,SMFDB,SNLB,SWBBL,USLB,VLBS,WOMI"
finances="BFC,CFCL,GFCL,GMFIL,GUFL,ICFC,JFL,MFIL,MPFL,NFS,pok,PROFL,RLFL,SFCL,SIFC" 
others= "NRIC,NTC"
hotels="CGH,OHL,SHL,TRH"
lifes="ALICL,GLICL,JLI,LICN,nepal life,NLICL,PLI,PLIC,RLI,SLICL"
non_lifes="AIL,EIC,GIC,HGI,IGI,LGIL,NICL,NIL,NLG,PIC,PICL,PRIN,RBCL,SGI,SIC,SICL,SIL,UIC"
hydros="AHPC,AKJCL,AKPL,API,BARUN,BPCL,CHCL,CHL,DHPL,GHL,GLH,HDHPC,HPPL,HURJA,JOSHI,KKHC,KPCL,LEC,MEN,MHNL,NGPL,NHDL,NHPC,PMHPL,PPCL,RADHI,RHPC,RHPL,RRHP,RURU,SHEL,SHPC,SJCL,SPDL,SSHL,UMHL,UMRH,UNHPL,UPCL,UPPER"
turns=lifes.split(',')
for turn in turns:
    pyautogui.write(turn,0.2)
    pyautogui.press('enter')
    pyautogui.press('tab')
    pyautogui.press('enter')
    pyautogui.hotkey('shift','tab')
    time.sleep(1)